# Site
name: 'WhiteDuck.Dev'
title: 'WhiteDuck.Dev'
description: 'Tudo sobre Tudo de Tecnologia ;D'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'whiteduck-dev'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ['_pages']
permalink: /:title/

# Authors
authors:
  eduardo:
    name: Eduardo Malherbi
    display_name: emalherbi
    gravatar: b4b2e05c730f60dd7ad3acb964bed758
    email: emalherbi@gmail.com
    web: https://www.emalherbi.com
    twitter: https://twitter.com/emalherbi
    linkedin: https://www.linkedin.com/in/emalherbi/
    description: 'Full-Stack Web Developer.'
  fernando:
    name: Fernando Derkoski de Souza
    display_name: brilvio
    gravatar: b2ba2f4fc67c38320b9291f230c53014
    email: brilvio@gmail.com
    web: https://www.derkoski.com
    twitter: https://twitter.com/brilvio
    linkedin: https://www.linkedin.com/in/derkoski/
    description: 'Full-Stack Developer'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: 'disabled'
adsense-data-ad-client: 'ca-pub-3412143450191416'
adsense-data-ad-slot: '1363087678'

# Lazy Images ("enabled" or "disabled")
lazyimages: 'disabled'

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
